jobs:
  increment-package-version:
    executor: vsce/node-browsers
    working_directory: ~/project/vsce-orb-integration-test
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - v1-node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-node-cache-{{ .Branch }}
            - v1-node-cache-
      - run: npm install
      - run: npm test
      - save_cache:
          key: v1-node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - add_ssh_keys:
          fingerprints:
            - ba:b7:1a:a1:82:db:ae:fa:75:8c:38:54:30:8e:10:29
      - vsce/configure-git
      - run: |
          git checkout master && \
          npm version patch && \
          cd .. && \
          git add . && \
          git commit -m "integration-test"
          git push origin master --force

orbs:
  orb-tools: circleci/orb-tools@9.0.0
  vsce: uraway/vsce@<<pipeline.parameters.dev-orb-version>>

parameters:
  dev-orb-version:
    default: 'dev:alpha'
    type: string
  run-integration-tests:
    default: false
    type: boolean
version: 2.1
workflows:
  integration-tests_prod-release:
    jobs:
      - increment-package-version
      - vsce/publish:
          publish-token-variable: VSCODE_MARKETPLACE_TOKEN
          push-git-tag: false
          package-path: vsce-orb-integration-test
          requires:
            - increment-package-version
      - orb-tools/dev-promote-prod-from-commit-subject:
          add-pr-comment: true
          fail-if-semver-not-indicated: true
          filters:
            branches:
              only: master
          orb-name: uraway/vsce
          publish-version-tag: false
          requires:
            - vsce/publish
    when: << pipeline.parameters.run-integration-tests >>
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: uraway/vsce
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
    unless: << pipeline.parameters.run-integration-tests >>
